language: java
jdk:
- oraclejdk8

before_script: cd springBootDemo
script: mvn verify -B

before_install:
- openssl aes-256-cbc -K $encrypted_4611c519b298_key -iv $encrypted_4611c519b298_iv
  -in cs4227_key.pem.enc -out cs4227_key.pem -d

before_deploy:
- cd ..
- pwd
- ls
- eval "$(ssh-agent -s)"
- chmod 600 cs4227_key.pem
- ssh-add cs4227_key.pem
deploy:
  provider: script
  skip_cleanup: true
  script:
  - ssh -oStrictHostKeyChecking=no -i "cs4227_key.pem" ubuntu@ec2-54-208-196-22.compute-1.amazonaws.com
    "cd SoftwareDesignAndArchitecture && git pull && cd springBootDemo && mvn clean install -DskipTests && nohup mvn spring-boot:run -DskipTests &"
  on:
    branch: fix-import
